<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $places=array(

            "ARIANA","BEJA","BEN AROUS","BIZERTE","GABES","GAFSA","JENDOUBA","KAIROUAN","KASSERINE","KEBILI","KEF","MAHDIA","MANOUBA","MEDENINE","MONASTIR","NABEUL","SFAX","SIDI BOUZID","SILIANA","SOUSSE","TATAOUINE","TOZEUR","TUNIS","ZAGHOUAN" ,

            "RAOUED , ARIANA","SIDI THABET , ARIANA","ARIANA VILLE , ARIANA","LA SOUKRA , ARIANA","KALAAT LANDLOUS , ARIANA","ETTADHAMEN , ARIANA","MNIHLA , ARIANA"

            , "BEJA NORD ,BEJA","NEFZA , BEJA","GOUBELLAT ,BEJA","MEJEZ EL BAB ,BEJA","AMDOUN , BEJA","TEBOURSOUK ,BEJA","TESTOUR , BEJA","THIBAR, BEJA","BEJA SUD BEJA"
           , "EZZAHRA ,BEN AROUS","MOHAMADIA ,BEN AROUS","RADES ,BEN AROUS","EL MOUROUJ ,BEN AROUS","FOUCHANA ,BEN AROUS","HAMMAM CHATT ,BEN AROUS","HAMMAM LIF ,BEN AROUS","MEGRINE ,BEN AROUS","NOUVELLE MEDINA ,BEN AROUS",
            "MORNAG ,BEN AROUS","BOU MHEL EL BASSATINE ,BEN AROUS"
            ,"MENZEL BOURGUIBA , BIZERTE","UTIQUE , BIZERTE","MENZEL JEMIL , BIZERTE", "BIZERTE NORD  , BIZERTE","BIZERTE SUD , BIZERTE","EL ALIA , BIZERTE","SEJNANE , BIZERTE","GHAR EL MELH , BIZERTE","GHEZALA","JARZOUNA , BIZERTE","JOUMINE","MATEUR , BIZERTE","RAS JEBEL  , BIZERTE" ,"TINJA , BIZERTE"
            ,"EL METOUIA , GABES","GABES MEDINA , GABES","GABES OUEST , GABES","GABES SUD , GABES","EL HAMMA , GABES","NOUVELLE MATMATA , GABES","MARETH","GHANNOUCHE , GABES","MATMATA , GABES","MENZEL HABIB , GABES"
            ,"BELKHIR , GAFSA","EL GUETTAR , GAFSA","EL KSAR ,GAFSA","EL MDHILLA ,GAFSA","SNED ,GAFSA","MOULARES ,GAFSA","REDEYEF ,GAFSA","SIDI AICH ,GAFSA","GAFSA SUD  ,GAFSA","METLAOUI ,GAFSA","GAFSA NORD ,GAFSA"

            ,"SBIKHA , KAIROUAN " ,"KAIROUAN SUD , KAIROUAN " ,"OUESLATIA , KAIROUAN " ,"NASRALLAH , KAIROUAN " ,"KAIROUAN NORD , KAIROUAN " ,"EL ALA , KAIROUAN " ,"HAJEB EL AYOUN , KAIROUAN " ,"CHEBIKA , KAIROUAN " ,"HAFFOUZ , KAIROUAN " ,"CHERARDA , KAIROUAN " ,"BOU HAJLA , KAIROUAN ",
            "FERNANA , JENDOUBA   " ,"GHARDIMAOU , JENDOUBA   " ,"TABARKA , JENDOUBA   "  ,"JENDOUBA NORD , JENDOUBA   " ,"AIN DRAHAM , JENDOUBA   " ,"OUED MLIZ , JENDOUBA   " ,"BOU SALEM , JENDOUBA   " ,"BALTA BOU AOUENE , JENDOUBA   ",
            "HAIDRA , KASSERINE  " ,"SBEITLA , KASSERINE  " ,"MEJEL BEL ABBES , KASSERINE  " ,"KASSERINE NORD , KASSERINE  " ,"EL AYOUN , KASSERINE  " ,"EZZOUHOUR , KASSERINE  " ,"FERIANA , KASSERINE  " ,"FOUSSANA , KASSERINE  " ,"HASSI EL FRID , KASSERINE  " ,"JEDILIANE , KASSERINE  " ,"KASSERINE SUD , KASSERINE  " ,"SBIBA , KASSERINE  " ,"THALA , KASSERINE  " ,
            "SOUK EL AHAD , KEBILI " ,"KEBILI SUD , KEBILI " ,"KEBILI NORD , KEBILI " ,"DOUZ , KEBILI " ,"EL FAOUAR , KEBILI ",
            "TAJEROUINE , EL KEF " ,"TOUIREF , EL KEF " ,"NEBEUR , EL KEF " ,"SAKIET SIDI YOUSSEF , EL KEF " ,"LE SERS , EL KEF " ,"EL KSOUR , EL KEF " ,"LE KEF EST , EL KEF " ,"DAHMANI , EL KEF " ,"KALAAT SINANE , EL KEF " ,"JERISSA , EL KEF " ,"KALAA EL KHASBA , EL KEF " ,"LE KEF OUEST , EL KEF " ,
            "MELLOULECH , MAHDIA " ,"SIDI ALOUENE , MAHDIA " ,"MAHDIA , MAHDIA " ,"SOUASSI , MAHDIA " ,"OULED CHAMAKH , MAHDIA " ,"BOU MERDES , MAHDIA " ,"CHORBANE , MAHDIA " ,"KSOUR ESSAF , MAHDIA " ,"HBIRA , MAHDIA " ,"LA CHEBBA , MAHDIA " ,"EL JEM , MAHDIA ",
            "BORJ EL AMRI , MANNOUBA " ,"JEDAIDA , MANNOUBA " ,"OUED ELLIL , MANNOUBA " ,"TEBOURBA , MANNOUBA " ,"EL BATTAN , MANNOUBA " ,"MANNOUBA , MANNOUBA " ,"MORNAGUIA , MANNOUBA " ,"DOUAR HICHER , MANNOUBA " ,
            "HOUMET ESSOUK , MEDENINE " ,"MEDENINE SUD , MEDENINE " ,"BENI KHEDACHE , MEDENINE " ,"SIDI MAKHLOUF , MEDENINE " ,"MIDOUN , MEDENINE " ,"ZARZIS , MEDENINE " ,"MEDENINE NORD , MEDENINE " ,"BEN GUERDANE , MEDENINE " ,"AJIM , MEDENINE " ,
            "SAYADA LAMTA BOU HAJAR , MONASTIR  " ,"KSIBET EL MEDIOUNI , MONASTIR  " ,"KSAR HELAL , MONASTIR  " ,"JEMMAL , MONASTIR  " ,"SAHLINE , MONASTIR  " ,"MONASTIR , MONASTIR  " ,"MOKNINE , MONASTIR  " ,"OUERDANINE , MONASTIR  " ,"TEBOULBA , MONASTIR  " ,"ZERAMDINE , MONASTIR  " ,"BEKALTA , MONASTIR  " ,"BEMBLA , MONASTIR  " ,"BENI HASSEN , MONASTIR  ",
            "KORBA , NABEUL  " ,"SOLIMAN , NABEUL  " ,"TAKELSA , NABEUL  " ,"MENZEL BOUZELFA , NABEUL  " ,"MENZEL TEMIME , NABEUL  " ,"NABEUL , NABEUL  " ,"BENI KHIAR , NABEUL  " ,"BENI KHALLED , NABEUL  " ,"HAMMAMET , NABEUL  " ,"EL HAOUARIA , NABEUL  " ,"KELIBIA , NABEUL  " ,"GROMBALIA , NABEUL  " ,"EL MIDA , NABEUL  " ,"BOU ARGOUB , NABEUL  " ,"DAR CHAABANE ELFEHRI , NABEUL  " ,"HAMMAM EL GHEZAZ , NABEUL  ",
            "EL HENCHA , SFAX  " ,"ESSKHIRA , SFAX  " ,"GHRAIBA , SFAX  " ,"EL AMRA , SFAX  " ,"BIR ALI BEN KHELIFA , SFAX  " ,"AGAREB , SFAX  " ,"SFAX VILLE , SFAX  " ,"SAKIET EDDAIER , SFAX  " ,"MAHRAS , SFAX  " ,"MENZEL CHAKER , SFAX  " ,"SFAX EST , SFAX  " ,"SFAX SUD , SFAX  " ,"JEBENIANA , SFAX  " ,"KERKENAH , SFAX  " ,"SAKIET EZZIT , SFAX  ",
            "ENNADHOUR , SIDI BOUZID " ,"EL FAHS , SIDI BOUZID " ,"BIR MCHERGA , SIDI BOUZID " ,"ZAGHOUAN , SIDI BOUZID " ,"HAMMAM ZRIBA , SIDI BOUZID " ,"SAOUEF , SIDI BOUZID ",
            "SILIANA SUD , SILIANA " ,"SIDI BOU ROUIS , SILIANA " ,"SILIANA NORD , SILIANA " ,"GAAFOUR , SILIANA " ,"KESRA , SILIANA " ,"LE KRIB , SILIANA " ,"BOU ARADA , SILIANA " ,"BARGOU , SILIANA " ,"MAKTHAR , SILIANA " ,"ROHIA , SILIANA " ,"EL AROUSSA , SILIANA ",
            "SIDI BOU ALI , SOUSSE " ,"SIDI EL HENI , SOUSSE " ,"SOUSSE JAOUHARA , SOUSSE " ,"SOUSSE RIADH , SOUSSE " ,"SOUSSE VILLE , SOUSSE " ,"BOU FICHA , SOUSSE " ,"AKOUDA , SOUSSE " ,"HAMMAM SOUSSE , SOUSSE " ,"KALAA ESSGHIRA , SOUSSE " ,"KONDAR , SOUSSE " ,"MSAKEN , SOUSSE " ,"ENFIDHA , SOUSSE " ,"HERGLA , SOUSSE " ,"KALAA EL KEBIRA , SOUSSE " ,"SOUSSE , SOUSSE ",
            "TATAOUINE SUD , TATAOUINE  " ,"BIR LAHMAR , TATAOUINE  " ,"DHEHIBA , TATAOUINE  " ,"GHOMRASSEN , TATAOUINE  " ,"TATAOUINE NORD , TATAOUINE  " ,"REMADA , TATAOUINE  " ,"SMAR , TATAOUINE  ",
            "DEGUECHE , TOZEUR " ,"TOZEUR , TOZEUR " ,"HEZOUA , TOZEUR " ,"NEFTA , TOZEUR " ,"TAMEGHZA , TOZEUR " ,
            "EL MENZAH , TUNIS " ,"EL HRAIRIA , TUNIS " ,"EL KABBARIA , TUNIS " ,"EL KRAM , TUNIS " ,"BAB SOUIKA , TUNIS " ,"CARTHAGE , TUNIS " ,"CITE EL KHADRA , TUNIS " ,"BAB BHAR , TUNIS " ,"LA MARSA , TUNIS " ,"EZZOUHOUR , TUNIS " ,"JEBEL JELLOUD , TUNIS " ,"SIDI EL BECHIR , TUNIS " ,"LA GOULETTE , TUNIS " ,"LE BARDO , TUNIS " ,"EL OMRANE , TUNIS " ,"EL OMRANE SUPERIEUR , TUNIS " ,"EL OUERDIA , TUNIS " ,"ETTAHRIR , TUNIS " ,"SIDI HASSINE , TUNIS " ,"ESSIJOUMI , TUNIS " ,"LA MEDINA , TUNIS ",
            "ENNADHOUR , ZAGHOUAN " ,"EL FAHS , ZAGHOUAN " ,"BIR MCHERGA , ZAGHOUAN "  ,"HAMMAM ZRIBA , ZAGHOUAN " ,"SAOUEF , ZAGHOUAN "
);

        foreach ($places as $place) {
            DB::table('places')->insert([
                'name' => $place,

            ]);
        }

    }
}
